### PR TITLE
5-cree-la-partie-presantation-des-logiciel

### LINKED ISSUE #5: Cree la partie presantation des logiciel
Entre le hero banner et le footer faudrais:

- 6 Logiciel priver avec 6 alternative gratuite et **LIBRE** a mettre dans des column de 3 donc en 2*3 chaque logiciel dois etre dans une div avec ça paire pour separer les paire et pouvoir gerer mieux

### PR DESCRIPTION
**Pull request by Zerbaib**

### CODE REVIEW

**Comment by Zerbaib** [comment]
do not merge now wait i need 1 commit

**Comment by Zerbaib** [comment]
@Guillaume0001 et voila

**Review by Guillaume0001 — COMMENTED** [review]
All's good

**Review by Guillaume0001 — APPROVED** [review]
All's good²

**Pull request merged**
